# override global pinning to stay on CUDA 12.0
# because CatBoost does not support CUDA versions 12.3+ yet: https://github.com/catboost/catboost/issues/2755
docker_image:                                       # [linux]
  - quay.io/condaforge/linux-anvil-x86_64:alma9     # [linux]
  - quay.io/condaforge/linux-anvil-x86_64-cuda11.8:ubi8  # [linux]
  - quay.io/condaforge/linux-anvil-x86_64:alma9     # [linux]
c_compiler_version:                                 # [linux]
  - 13                                              # [linux]
  - 11                                              # [linux]
  - 12                                              # [linux]
cxx_compiler_version:                               # [linux]
  - 13                                              # [linux]
  - 11                                              # [linux]
  - 12                                              # [linux]
fortran_compiler_version:                           # [linux]
  - 13                                              # [linux]
  - 11                                              # [linux]
  - 12                                              # [linux]
cuda_compiler:                                      # [linux]
  - None                                            # [linux]
  - nvcc                                            # [linux]
  - cuda-nvcc                                       # [linux]
cuda_compiler_version:                              # [linux]
  - None                                            # [linux]
  - 11.8                                            # [linux]
  - 12.0                                            # [linux]
